config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/about'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :tasks

  validates :name, presence: true, length: { maximum:50 }
  validates :content, presence: true, length: { maximum:500 }
  validates :price, presence: true, numericality: { only_integer: true }

  has_attached_file :image,
    styles: { medium: "680x300>", thumb: "170x75>" }

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\z/

  def shortname
    name.length > 25? name[0..25] + "..." : name
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :project

  validates :title, presence: true, length: { maximum:50 }
  validates :video, presence: true
  validates :tag, presence: true
  validates :project, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def self.find_for_google_oauth2(auth, signed_in_resource = nil)
    data = auth.info
    user = User.where(:email => data["email"]).first

     unless user
         user = User.create(first_name: data["first_name"],
            last_name: data["last_name"],
            email: data["email"],
            image: data["image"],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:first_name, :last_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @projects =  Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(:tag)
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def show
    project = Project.find(params[:project_id])
    @tasks = project.tasks.order(:tag)
    @task = @tasks.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2

      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
      #@user = User.find_for_google_auth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :striketrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magikme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<%= render partial: "shared/header" %>
<%= render partial: "shared/message" %>

  <main>

    <div class="container">
      <%= yield %>
    </div>

  </main>

<%= render partial: "shared/footer" %>

</body>

<script>
$(document).ready(function(){
$(".button-collapse").sideNav();

$(".dropdown-button").dropdown();

});
</script>

</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/project/index.html.erb
<div class="row">
<br />

<% @projects.each do |project| %>
    <%= link_to project do %>
      <div class="col s12 m6 l4">
        <div class="card">

          <div class="card-image waves-effect waves-block waves-light">
            <%= image_tag project.image %>
          </div>

          <div class="card-content style="height: 6em>
            <span class="card-title grey-text text-darken-4">
              <%= project.shortname %>
            </span>
            </div>
        </div>
      </div>
    <% end %>
<% end %>
</div>

app/views/project/show.html.erb
<div class="row">
  <div class="col m4">
    <div class="card z-depth-2">
      <div class="center">
        <br />
        <h1><%= @project.price %>€</h1>
      </div>
      <div class="card-action center">
        <button class="btn waves-effect waves-light pink darken-2">
           Take this Project
        </button>
      </div>
    </div>
  </div>

  <div class="col m8">
    <div class="card z-depth-2">
      <div class="card-image">
        <%= image_tag @project.image %>
      </div>
      <div class="card-content grey-text text-darken-4">
        <h5><%= @project.name %></h5>
        <hr>
        <%= @project.content %>

        <div class="collection">
          <% @tasks.each do |task| %>
            <% if task.header %>
              <div class="collection-item active">
                <i class="mdi-social-school"> <%= task.title %></i>
              </div>
            <% else %>
              <%= link_to [task.project, task], class: "collection-item" do %>
                <%= task.title %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_devisesmes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer teal accent-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Magik.me</h5>
        <p class="grey-text text-lighten-4">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Partners</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">x</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">yyy</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">zzzzzz</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright Magik.me
     <%= link_to "About", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">My Goals</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">My Goals</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

<header>

  <nav>
   <nav class="teal accent-4 z-depth-2">
    <div class="container">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo"><i class="medium mdi-action-grade"> magik.me</i></a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">

          <% if (!user_signed_in?) %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
              <li><a href="#">Goals</a></li>
              <li><a class="dropdown-button" href="#!" data-activates="dropdown1">

                <% if current_user.image %>
                  <div class="chip"> <%= image_tag current_user.image %><%= current_user.first_name %></div><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                <% else %>
                <div class="chip"> <%= image_tag "http://placehold.it/48x48" %></div><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                <% end %>


        <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="#">Goals</a></li>
           <% if (!user_signed_in?) %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
              <li><a href="#">Goals</a></li>
              <li><a class="dropdown-button" href="#!" data-activates="dropdown2">

                <% if current_user.image %>
                  <div class="chip"> <%= image_tag current_user.image %><%= current_user.first_name %></div><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                <% else %>
                <div class="chip"> <%= image_tag "http://placehold.it/48x48" %></div><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                <% end %>


        <% end %>
        </ul>
      </div>
    </div>
   </nav>
  </nav>

  </header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/task/show.html.erb
<div class="row">
  <div class="col m4">
    <div class="card z-depth-2">
      <div class="card-content">
        <div class="collection">
          <% @tasks.each do |task| %>
          <% if task.header %>
            <div class="collection-item active">
              <i class="mdi-social-school"> <%= task.title %></i>
            </div>
          <% else %>
            <%= link_to [task.project, task], class: "collection-item" do %>
              <%= task.title %>
            <% end %>
          <% end %>
        <% end %>
        </div>

      </div>
    </div>
  </div>

<div class="col m8">
    <div class="card z-depth-2">
        <div class="content">
          <%= @task.video %>
        </div>
        <div class="card-action grey-text text-darken-4">
          <h5><%= @task.title %></h5>
          <hr>
          <%= markdown(@task.note) %>
        </div>
    </div>
</div>

</div>